Fix readonly param
The param takes the on/off values, but %t formats the boolean as true/false.

Error before this commit:

```
qemu-system-x86_64: -fsdev local,id=sd-9p-0,path=/tmp/go-build1305099592/b001,readonly=false,security_model=none,multidevs=remap: Parameter 'readonly' expects 'on' or 'off'
Error: exec: qemu: exit status 1
```

Signed-off-by: Mauricio Vásquez <mauriciov@microsoft.com>