Revert "work around race in virtio serial console"
This reverts commit 475850de399c51e7a39da10adb34dc6d54e9294f.

It seems that kernels < 6.1 suffer from a separate lost wakeup
problem which manifests in reads of the control message timing
out:

    [    1.312132] Run /home/runner/go/bin/vimto as init process
    Error: read command: read /dev/vport2p1: i/o timeout
    [    3.144910] ACPI: Preparing to enter system sleep state S5